### ISSUE TITLE
Protocol timeout

### ISSUE THREAD

**Issue by Meemaw** [foo-software/lighthouse-check-action#58]
Lately we've been seeing a lot of protocol timeout errors using this action. Is this a known issue/are there any workarounds to increase that timeout?

```
Run foo-software/lighthouse-check-action@v4.0.0
lighthouse-check: Auditing mobile (1/4): http://localhost:3000
lighthouse-check:
 LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/home/runner/work/_actions/foo-software/lighthouse-check-action/v4.0.0/node_modules/lighthouse/lighthouse-core/gather/driver.js:322:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'LHError',
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)',
  lhrRuntimeError: true,
  protocolMethod: 'Network.emulateNetworkConditions'
}
Error: PROTOCOL_TIMEOUT
```

**Comment by adamhenson** [comment]
Hello @Meemaw this is actually a Lighthouse issue. Unfortunately per the issue below, there isn't a solid solution. Not all URLs are impacted.

https://github.com/GoogleChrome/lighthouse/issues/6512
